version: "3.9"

services:
  backend:
    build: .
    container_name: qr-backend
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
